### PR TITLE
Implement GitHub Actions

### LINKED ISSUE #21: Move from Travis CI to GitHub Actions?
Would you be interested in a pull request that moves CI from Travis CI to GitHub Actions, or at least adds GitHub Actions alongside Travis CI? It seems travis-ci.org will stop being useful from Dec 31 2020. I can do it, except that I think you need to create the workflow yml, first, in `master`, after which I can branch off of.

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**
~~You might also want to reference the "build" status in `README.md`.~~

I think you need to "activate" GitHub Actions on `master` after which I can rebase this for testing.

Closes #21.

### CODE REVIEW

**Comment by paulo-ferraz-oliveira** [comment]
> You might also want to reference the "build" status in README.md.

Don't merge just yet. Let me do this, while I'm at it.

**Comment by deadtrickster** [comment]
I'm ready to merge, shall I?

**Comment by paulo-ferraz-oliveira** [comment]
Yes, thanks.

**Comment by deadtrickster** [comment]
Thank you, anything else I shall do?

**Comment by paulo-ferraz-oliveira** [comment]
Nothing else is required. If it doesn't work after merge I'll PR again to fix it. The "problem" with this flow is that the Action has to exist prior to subsequent pull requests, but that condition is now fulfilled.

**Pull request merged**
